# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Okteto Push
        # You may pin to the exact commit or the version.
        # uses: okteto/push@8ee0a740f2771fa845abe43b97b2d9b364acc40d
        uses: okteto/push@1.14.5
        with:
          # If present, the namespace scope for this action. If not specified, it will use the current context
          namespace: albverhoy
          # The name of the deployment. If missing it will use the one in your okteto.yml file
          name: consulta-cedula
          # Create the deployment if it doesn't exist in the namespace. If not specified, the action will fail if the deployment doesn't exist
          deploy: true
